# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authusers',
            name='au_avatar',
            field=models.ImageField(blank=True, upload_to='users_avatars', verbose_name='avatar'),
        ),
    ]
