# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CollectionsImg', verbose_name='product'),
        ),
    ]
