# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 11:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='basket_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.CollectionsImg', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='basket_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
