# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionsimg',
            old_name='collection_img',
            new_name='img_collections',
        ),
    ]
