# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_collectionsimg_img_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collections',
            name='collection_is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
