# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-24 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171124_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionsimg',
            old_name='img_collections',
            new_name='img_collection',
        ),
    ]
